'use strict';

var gulp = require('gulp');
var batch = require('gulp-batch');
var watch = require('gulp-watch');
var babel = require("gulp-babel");
var insert = require('gulp-insert');

var spawn = require('child_process').spawn;
var node;

gulp.task("transpile", function () {
    gulp.src(["./jobs/**/*.js6"])
    .pipe(babel())
    .pipe(insert.prepend("/**\n*\n* DO NOT EDIT THIS FILE. EDIT .js6 INSTEAD\n*\n*/\n\n"))
    .pipe(gulp.dest("./jobs"));
});

gulp.task('start', function () {
  if (node) {
    node.kill('SIGKILL');
  }
  node = spawn('node', ['./bin/processing'], { stdio: 'inherit' });
  node.on('close', function (code) {
    if (code === 8) {
      gulp.log('Error detected, waiting for changes...');
    }
  });
});

gulp.task('start-dev', ['start'], function () {
  watch('./**/*.js', batch(function (events, done) {

    gulp.start('transpile');
    gulp.start('start', done);
  }));
});

gulp.task('default', ['transpile', 'start']);

// clean up if an error goes unhandled.
process.on('exit', function () {
  if (node) {
    node.kill();
  }
});
